USE [PRESALE_FARM]
GO
-- =============================================
-- Autor:					diego.as
-- Fecha de Creacion: 		3/31/2017
-- Description:			    Tabla para almacenar los productos del catalogo 

/*
-- Ejemplo de Ejecucion:
        SELECT * FROM [presalefarm].[PRODUCT_CATALOG]
*/
-- =============================================
CREATE TABLE [presalefarm].[PRODUCT_CATALOG] (
	[ID] INT IDENTITY(1,1)
	,[CODE_SKU] VARCHAR(150) NOT NULL
	,[DESCRIPTION_SKU] VARCHAR(250) NOT NULL
	,[HANDLE_SERIAL] INT NOT NULL
	,PRIMARY KEY ([ID])
)

/*
INSERT INTO PRESALEFARM.PRODUCT_CATALOG([CODE_SKU],[DESCRIPTION_SKU],[HANDLE_SERIAL]) VALUES('10001','PRUEBA SKU1',0);
INSERT INTO PRESALEFARM.PRODUCT_CATALOG([CODE_SKU],[DESCRIPTION_SKU],[HANDLE_SERIAL]) VALUES('10002','PRUEBA SKU2',0);
INSERT INTO PRESALEFARM.PRODUCT_CATALOG([CODE_SKU],[DESCRIPTION_SKU],[HANDLE_SERIAL]) VALUES('10003','PRUEBA SKU3',0);
INSERT INTO PRESALEFARM.PRODUCT_CATALOG([CODE_SKU],[DESCRIPTION_SKU],[HANDLE_SERIAL]) VALUES('10004','PRUEBA SKU4',0);
INSERT INTO PRESALEFARM.PRODUCT_CATALOG([CODE_SKU],[DESCRIPTION_SKU],[HANDLE_SERIAL]) VALUES('10005','PRUEBA SKU5',0);
*/